<?php
/**
 * DEVTA — Hostinger Database Setup Wizard
 * Open once after upload: https://yourdomain.com/install.php
 * Delete this file after successful setup.
 */

error_reporting(E_ALL);
ini_set('display_errors', '0');

$lockFile   = __DIR__ . '/database/installed.lock';
$localFile  = __DIR__ . '/backend/config.local.php';
$isInstalled = is_file($lockFile) && is_file($localFile);

$success = '';
$error   = '';
$stepOk  = false;

function h(?string $v): string
{
    return htmlspecialchars($v ?? '', ENT_QUOTES, 'UTF-8');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($isInstalled && empty($_POST['force'])) {
        $error = 'Already installed. Delete database/installed.lock to run setup again.';
    } else {
        $host = trim($_POST['db_host'] ?? 'localhost');
        $name = trim($_POST['db_name'] ?? '');
        $user = trim($_POST['db_user'] ?? '');
        $pass = (string) ($_POST['db_pass'] ?? '');

        if ($host === '' || $name === '' || $user === '') {
            $error = 'Host, Database name aur Username required hain.';
        } else {
            try {
                $dsn = 'mysql:host=' . $host . ';dbname=' . $name . ';charset=utf8mb4';
                $pdo = new PDO($dsn, $user, $pass, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                ]);

                // Create tables
                $pdo->exec("CREATE TABLE IF NOT EXISTS users (
                    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                    username VARCHAR(50) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

                $pdo->exec("CREATE TABLE IF NOT EXISTS contacts (
                    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(150) NOT NULL,
                    message TEXT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

                $pdo->exec("CREATE TABLE IF NOT EXISTS service_requests (
                    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(150) NOT NULL,
                    phone VARCHAR(20) NOT NULL,
                    service VARCHAR(150) NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    INDEX idx_service (service),
                    INDEX idx_created (created_at)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

                $hash = password_hash('Nico@871', PASSWORD_DEFAULT);
                $stmt = $pdo->prepare(
                    'INSERT INTO users (username, password) VALUES (:u, :p)
                     ON DUPLICATE KEY UPDATE password = VALUES(password)'
                );
                $stmt->execute([':u' => 'Devtaknowledge', ':p' => $hash]);

                // Remove old default admin if present
                $pdo->prepare('DELETE FROM users WHERE username = :old AND username <> :new')
                    ->execute([':old' => 'admin', ':new' => 'Devtaknowledge']);

                // Write config.local.php
                $exportPass = var_export($pass, true);
                $content = "<?php\n"
                    . "/**\n * Hostinger MySQL credentials — auto-generated by install.php\n */\n"
                    . "define('DB_DRIVER', 'mysql');\n"
                    . "define('DB_HOST', " . var_export($host, true) . ");\n"
                    . "define('DB_NAME', " . var_export($name, true) . ");\n"
                    . "define('DB_USER', " . var_export($user, true) . ");\n"
                    . "define('DB_PASS', {$exportPass});\n"
                    . "define('DB_CHARSET', 'utf8mb4');\n";

                if (file_put_contents($localFile, $content) === false) {
                    throw new RuntimeException('config.local.php write nahi ho paya. backend folder writable rakho.');
                }

                if (!is_dir(__DIR__ . '/database')) {
                    mkdir(__DIR__ . '/database', 0755, true);
                }
                file_put_contents(
                    $lockFile,
                    "Installed: " . date('c') . "\nDB: {$name}\nHost: {$host}\n"
                );

                $success = 'Database connected & tables ready! Ab install.php delete kar do.';
                $stepOk = true;
                $isInstalled = true;
            } catch (Throwable $e) {
                $error = 'Connection/Setup failed: ' . $e->getMessage();
            }
        }
    }
}

$prefill = [
    'db_host' => $_POST['db_host'] ?? 'localhost',
    'db_name' => $_POST['db_name'] ?? '',
    'db_user' => $_POST['db_user'] ?? '',
];
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DEVTA — Hostinger DB Setup</title>
  <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@500;700;800&display=swap" rel="stylesheet" />
  <style>
    :root { --bg:#0b0f19; --card:#111827; --green:#00ff88; --text:#fff; --muted:#9ca3af; --err:#f87171; }
    * { box-sizing:border-box; margin:0; padding:0; }
    body { font-family:Manrope,system-ui,sans-serif; background:linear-gradient(160deg,#0b0f19,#111827); color:var(--text); min-height:100vh; display:grid; place-items:center; padding:1.5rem; }
    .card { width:min(520px,100%); background:rgba(17,24,39,.85); border:1px solid rgba(0,255,136,.2); border-radius:20px; padding:2rem; box-shadow:0 0 40px rgba(0,255,136,.1); }
    h1 { font-size:1.45rem; margin-bottom:.4rem; }
    p { color:var(--muted); font-size:.92rem; margin-bottom:1.25rem; line-height:1.5; }
    label { display:block; font-size:.82rem; color:var(--muted); margin:0 0 .35rem; font-weight:700; }
    input { width:100%; padding:.85rem 1rem; border-radius:12px; border:1px solid rgba(255,255,255,.1); background:rgba(11,15,25,.8); color:#fff; margin-bottom:1rem; font:inherit; }
    input:focus { outline:none; border-color:rgba(0,255,136,.45); box-shadow:0 0 0 3px rgba(0,255,136,.12); }
    button { width:100%; padding:.95rem; border:none; border-radius:12px; font:inherit; font-weight:800; cursor:pointer; background:linear-gradient(135deg,#0bc965,#059347); color:#04140c; }
    button:hover { box-shadow:0 0 24px rgba(0,255,136,.35); }
    .alert { padding:.8rem 1rem; border-radius:10px; margin-bottom:1rem; font-size:.9rem; }
    .ok { background:rgba(11,201,101,.12); border:1px solid rgba(0,255,136,.35); color:var(--green); }
    .bad { background:rgba(248,113,113,.12); border:1px solid rgba(248,113,113,.35); color:var(--err); }
    .steps { background:rgba(0,0,0,.25); border-radius:12px; padding:1rem; margin-bottom:1.25rem; font-size:.86rem; color:var(--muted); }
    .steps ol { margin-left:1.1rem; }
    .steps li { margin:.35rem 0; }
    .links { display:flex; gap:.75rem; flex-wrap:wrap; margin-top:1rem; }
    .links a { color:var(--green); font-weight:700; font-size:.9rem; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Hostinger Database Setup</h1>
    <p>MySQL details hPanel se copy karke yahan paste karo. Tables auto create ho jayenge.</p>

    <div class="steps">
      <strong style="color:#fff">hPanel steps:</strong>
      <ol>
        <li>Databases → <b>MySQL Databases</b></li>
        <li>Create database + user (All Privileges)</li>
        <li>Neeche form mein woh details daalo</li>
        <li>Success ke baad <b>install.php delete</b> kar do</li>
      </ol>
    </div>

    <?php if ($success): ?>
      <div class="alert ok"><?= h($success) ?></div>
      <div class="links">
        <a href="backend/ping.php">Test DB (ping.php)</a>
        <a href="admin/">Admin Login</a>
        <a href="frontend/index.html">Website</a>
      </div>
      <p style="margin-top:1rem">Admin: <b>Devtaknowledge</b> / <b>Nico@871</b></p>
    <?php endif; ?>

    <?php if ($error): ?>
      <div class="alert bad"><?= h($error) ?></div>
    <?php endif; ?>

    <?php if (!$stepOk): ?>
      <form method="POST" action="">
        <label for="db_host">DB Host</label>
        <input id="db_host" name="db_host" value="<?= h($prefill['db_host']) ?>" required />

        <label for="db_name">Database Name (e.g. u123_mydevta)</label>
        <input id="db_name" name="db_name" value="<?= h($prefill['db_name']) ?>" required placeholder="u123456789_mydevta" />

        <label for="db_user">Database Username</label>
        <input id="db_user" name="db_user" value="<?= h($prefill['db_user']) ?>" required placeholder="u123456789_admin" />

        <label for="db_pass">Database Password</label>
        <input id="db_pass" name="db_pass" type="password" required placeholder="Your MySQL password" />

        <?php if ($isInstalled): ?>
          <label style="display:flex;align-items:center;gap:.5rem;margin-bottom:1rem;font-weight:600">
            <input type="checkbox" name="force" value="1" style="width:auto;margin:0" /> Re-install / overwrite config
          </label>
        <?php endif; ?>

        <button type="submit">Connect &amp; Create Tables</button>
      </form>
    <?php endif; ?>
  </div>
</body>
</html>
